// apps/game-of-life/src/components/ProgressRing.jsx
/**
 * ProgressRing - Circular progress indicator
 */
export default function ProgressRing({ percentage, size = 120, strokeWidth = 8 }) {
    const radius = (size - strokeWidth) / 2
    const circumference = radius * 2 * Math.PI
    const offset = circumference - (percentage / 100) * circumference

    return (
        <svg width={size} height={size} className="progress-ring">
            {/* Background circle */}
            <circle
                stroke="#E5E7EB"
                fill="transparent"
                strokeWidth={strokeWidth}
                r={radius}
                cx={size / 2}
                cy={size / 2}
            />
            {/* Progress circle */}
            <circle
                stroke="#22C55E"
                fill="transparent"
                strokeWidth={strokeWidth}
                strokeLinecap="round"
                r={radius}
                cx={size / 2}
                cy={size / 2}
                style={{
                    strokeDasharray: circumference,
                    strokeDashoffset: offset
                }}
            />
            {/* Center text */}
            <text
                x="50%"
                y="50%"
                textAnchor="middle"
                dominantBaseline="middle"
                className="text-3xl font-bold fill-[var(--gol-text)]"
                style={{ transform: 'rotate(90deg)', transformOrigin: 'center' }}
            >
                {percentage}%
            </text>
        </svg>
    )
}

// apps/sant-darshan-pwa/src/lib/components/ui/ProgressRing.svelte
<script lang="ts">
    import { cn } from "$lib/utils";

    let {
        progress = 0,
        size = 120,
        strokeWidth = 8,
        color = "text-primary",
        trackColor = "text-primary/20",
        class: className = "",
        children,
    } = $props();

    // Calculate circle path
    let radius = $derived((size - strokeWidth) / 2);
    let circumference = $derived(radius * 2 * Math.PI);

    // Derived value for dash offset
    let offset = $derived(circumference - (progress / 100) * circumference);
</script>

<div
    class={cn("relative inline-flex items-center justify-center", className)}
    style="width: {size}px; height: {size}px;"
>
    <!-- Background Track -->
    <svg class="w-full h-full transform -rotate-90" width={size} height={size}>
        <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            stroke="currentColor"
            stroke-width={strokeWidth}
            fill="transparent"
            class={cn("transition-all duration-300", trackColor)}
        />

        <!-- Progress Ring -->
        <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            stroke="currentColor"
            stroke-width={strokeWidth}
            fill="transparent"
            stroke-dasharray={circumference}
            stroke-dashoffset={offset}
            stroke-linecap="round"
            class={cn("transition-all duration-1000 ease-out", color)}
        />
    </svg>

    <!-- Center Content -->
    {#if children}
        <div class="absolute inset-0 flex items-center justify-center">
            {@render children()}
        </div>
    {/if}
</div>
